url: https://alexharkess.github.io

# Site settings
title: Alex Harkess
email: aharkess@plantbio.uga.edu
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: 333 
  secondary-dark: 000

# Team names, titles and social links
people:
- name: Jeremy Ray
  pic: 1
  position: Senior, Plant Biology. <br /> Comparative genomics of sex-linked genes
  social:
    - title: envelope
      url: mailto:jrmry@gmail.com

- name: Shayan Agha
  pic: 2
  position: Sophomore, Economics/Pre-med. <br /> Performing FISH-based analysis of sex-linked genes
  social:
    - title: envelope
      url: mailto:agha@uga.edu

- name: Dat Hoang
  pic: 3
  position: M.S Microbiology (2012). <br /> Virus Induced Gene Silencing in Asparagus
  social:
    - title: envelope
      url: mailto:dhoang@plantbio.uga.edu

- name: Saravanaraj Ayyampalayam
  pic: 4
  position: PhD Chemistry (1999)
  social:
    - title: envelope
      url: mailto:raj@plantbio.uga.edu

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/aeharkess
  - title: github
    url: http://github.com/alexharkess
  - title: envelope
    url: mailto:aharkess@plantbio.uga.edu

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty