url: https://alexharkess.github.io

# Site settings
title: Alex Harkess
email: aharkess@plantbio.uga.edu
description: "Alex Harkess, sex chromosomes, dioecy"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: 333 
  secondary-dark: 000

# Team names, titles and social links
people:
- name: Jeremy Ray
  pic: 1
  position: BS, Plant Biology (2014). <br /> Comparative genomics of sex-linked genes
  social:
    - title: envelope
      url: mailto:jrmry@gmail.com

- name: Shayan Agha
  pic: 2
  position: Sophomore, Economics/Pre-med. <br /> Performing FISH-based analysis of sex-linked genes
  social:
    - title: envelope
      url: mailto:agha@uga.edu

- name: Dat Hoang
  pic: 3
  position: M.S Microbiology (2012). <br /> Virus Induced Gene Silencing in Asparagus
  social:
    - title: envelope
      url: mailto:dhoang@plantbio.uga.edu

- name: Saravanaraj Ayyampalayam
  pic: 4
  position: PhD Chemistry (1999) <br /> Maintains our servers, data, and anything under the sun 
  social:
    - title: envelope
      url: mailto:raj@plantbio.uga.edu
      
- name: John Chaknis
  pic: 5
  position: Freshman, Pre-Dental <br /> FISH-based analysis of centromeres, telomeres, and sex-linked genes 
  social:
    - title: envelope
      url: mailto:test@plantbio.uga.edu
      
- name: Nekhil Patel
  pic: 6
  position: Senior, Anthropology <br /> Comparative genomics of sex-linked genes 
  social:
    - title: envelope
      url: mailto:test@plantbio.uga.edu
      
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/aeharkess
  - title: git
    url: http://github.com/alexharkess
  - title: envelope
    url: mailto:aharkess@plantbio.uga.edu
  - title: google
    url: http://scholar.google.com/citations?user=EkrN6nAAAAAJ&hl=en

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty